### ISSUE TITLE
Redo https://docs.railsbridgeboston.org/docs/

### ISSUE THREAD

**Issue by jacklynhma** [railsbridge-boston/docs-hardfork#139]
Update by @pcai aug 17, 2023:

Melissa and I chatted, we agreed to be a bit more incrementalist about these changes and use a [fork](https://github.com/railsbridge-boston/new-docs) of the [upstream repo](https://github.com/railsbridge/docs) as a starting point for changes. One goal is to preserve the structure of the code a little bit so any updates / improvements to the content can be merged upstream.

Google doc here: https://docs.google.com/document/d/1Zg_T9P-tQP4I65Ix27P9LJ_W5vs4jnSq8nD45NRbCtY/edit

**Comment by pcai** [comment]
Feel free to push directly to this branch (we can review when we pr into main): https://github.com/railsbridge-boston/docs/tree/pc-jekyll

this will automatically build and preview here http://railsbridge-boston.github.io/docs/ 

once we're happy with it we can deploy it live and replace https://docs.railsbridgeboston.org/docs/

**Comment by pcai** [comment]
i close this for now so we can focus on blockers for putting on the event
