### ISSUE TITLE
Microsoft NERD - Possible Venue?

### ISSUE THREAD

**Issue by jacklynhma** [railsbridge-boston/docs-hardfork#143]

**Comment by mxie** [comment]
I reached out to someone at Microsoft on June 14 and they referred me too [this form](https://www.microsoftnewengland.com/events-request/).  I filled it out and put myself as the “Microsoft Speaker”. They said I’d hear back within a week but still no word yet. I just sent a follow up email.

**Comment by mxie** [comment]
We were able to secure the venue for October 21! Will link more details later.
