### ISSUE TITLE
Investigate how we will use codespaces

### ISSUE THREAD

**Issue by jacklynhma** [railsbridge-boston/docs-hardfork#148]

**Comment by pcai** [comment]
this seems to work great and I was able to make a template repo here https://github.com/railsbridge-boston/start that anyone can immediately copy into a personal account and boot a codespace in about 5min with the correct ruby + rails installed, and in a sanity test i was able to get about halfway through the curriculum (e.g., the web server works, sqlite works, the instructions as-is are pretty close and require only minimal modifications for codespaces). **Any objections or suggestions if I start drafting replacement text to refer exclusively to codespaces this week?**

**Comment by pcai** [comment]
actually we can just link students to https://github.com/railsbridge-boston/start/generate

**Comment by pcai** [comment]
Draft here http://railsbridge-boston.github.io/docs/

having a readme.md in the tenplate repo causes problems because it causes rails new to prompt to replace the file

**Comment by pcai** [comment]
fixed and merged in https://github.com/railsbridge-boston/docs/commit/abb406c459b1982ea9fa8fa63da7aad457ae4894
