### ISSUE TITLE
This repo is not a fork

### ISSUE THREAD

**Issue by decklin** [railsbridge-boston/docs-hardfork#23]
I created this branch picking commits in master that could be merged cleanly upstream:

https://github.com/railsbridge-boston/docs/compare/ruby-edits-bos-201409

However, I can't actually do a cross-repository pull request to https://github.com/railsbridge/docs because this repo wasn't created in GitHub as a "fork". I guess they only look at this bit of metadata on their side even if the base commits are the same. I think we might need to recreate the repo and then re-push everything. In theory, this is easy, but I don't want to interrupt anyone's work if there are weird edge cases.

**Comment by decklin** [comment]
Sent a request into GitHub support on this.

**Comment by mxie** [comment]
@decklin Any updates so far?

**Comment by decklin** [comment]
Did not hear back from support yet.

**Comment by mxie** [comment]
@decklin Anything =\?

**Comment by pcai** [comment]
fixed, official fork is https://github.com/railsbridge-boston/docs
